# Generated by Django 3.2 on 2021-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
