# Generated by Django 3.2 on 2021-05-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_rename_calls_advisorcalls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvisorCalls',
            new_name='Calls',
        ),
    ]
